### ISSUE TITLE
안드로이드 9.0 에서 네이버 로그인시 앱이 종료되는 현상이 발생합니다.

### ISSUE THREAD

**Issue by halfelf11** [GwonHyeok/cordova-plugin-naver#13]
안드로이드 9.0 버전에서 네이버아이디로로그인 사용시 아이디 비번 입력후 개인정보 동의 부분에서 동의 버튼을 누르면 앱이 종료되는 현상이 발생합니다.

* 개발환경

cli packages: (/Users/****/.nvm/versions/node/v10.4.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.2.3
    Cordova Platforms  : android 8.0.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.3

System:

    ios-deploy : 1.9.4 
    Node       : v10.4.0
    npm        : 6.1.0 
    OS         : macOS
    Xcode      : Xcode 10.2.1 Build version 10E1001 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
		
		
* 사용 플러그인 
  "cordova-plugin-naver": "^1.0.3"
	"ionic-plugin-naver": "^1.0.3"
	
* app crash  당시 로그캣 내용

    --------- beginning of crash
2019-04-30 17:14:24.719 3721-5487/com.tokmom.testapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.tokmom.testapp, PID: 3721
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
        at com.nhn.android.naverlogin.connection.CommonConnection.getDefaultHttpClient(CommonConnection.java:204)
        at com.nhn.android.naverlogin.connection.CommonConnection.getDefaultHttpClient(CommonConnection.java:190)
        at com.nhn.android.naverlogin.connection.CommonConnection.getDefaultHttpClient(CommonConnection.java:186)
        at com.nhn.android.naverlogin.connection.CommonConnection.request(CommonConnection.java:106)
        at com.nhn.android.naverlogin.connection.CommonConnection.request(CommonConnection.java:53)
        at com.nhn.android.naverlogin.connection.CommonConnection.request(CommonConnection.java:44)
        at com.nhn.android.naverlogin.connection.OAuthLoginConnection.request(OAuthLoginConnection.java:52)
        at com.nhn.android.naverlogin.connection.OAuthLoginConnection.requestAccessToken(OAuthLoginConnection.java:34)
        at com.nhn.android.naverlogin.ui.OAuthLoginActivity$GetAccessTokenTask.doInBackground(OAuthLoginActivity.java:310)
        at com.nhn.android.naverlogin.ui.OAuthLoginActivity$GetAccessTokenTask.doInBackground(OAuthLoginActivity.java:1)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.DefaultHttpClient" on path: DexPathList[[zip file "/data/app/com.tokmom.testapp-wNijitTxo3aADtpWBnHHew==/base.apk"],nativeLibraryDirectories=[/data/app/com.tokmom.testapp-wNijitTxo3aADtpWBnHHew==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.nhn.android.naverlogin.connection.CommonConnection.getDefaultHttpClient(CommonConnection.java:204) 
        at com.nhn.android.naverlogin.connection.CommonConnection.getDefaultHttpClient(CommonConnection.java:190) 
        at com.nhn.android.naverlogin.connection.CommonConnection.getDefaultHttpClient(CommonConnection.java:186) 
        at com.nhn.android.naverlogin.connection.CommonConnection.request(CommonConnection.java:106) 
        at com.nhn.android.naverlogin.connection.CommonConnection.request(CommonConnection.java:53) 
        at com.nhn.android.naverlogin.connection.CommonConnection.request(CommonConnection.java:44) 
        at com.nhn.android.naverlogin.connection.OAuthLoginConnection.request(OAuthLoginConnection.java:52) 
        at com.nhn.android.naverlogin.connection.OAuthLoginConnection.requestAccessToken(OAuthLoginConnection.java:34) 
        at com.nhn.android.naverlogin.ui.OAuthLoginActivity$GetAccessTokenTask.doInBackground(OAuthLoginActivity.java:310) 
        at com.nhn.android.naverlogin.ui.OAuthLoginActivity$GetAccessTokenTask.doInBackground(OAuthLoginActivity.java:1) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by klaudbear** [comment]
config.xml 에
`    <config-file file="app/src/main/AndroidManifest.xml" parent="/manifest/application">
        <uses-library android:name="org.apache.http.legacy" android:required="false" />
    </config-file>`
넣어보세요.

https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

**Comment by monkeymarco** [comment]
cordova 10.0.0 사용중입니다.
동일한 현상이 발생하고있는데 해결되었나요?
