### ISSUE TITLE
TypeError: core_1.Cordova is not a function

### ISSUE THREAD

**Issue by tree1891** [GwonHyeok/cordova-plugin-naver#14]
cordova-plugin-naver 추가후 앱 실행시 발생하는 오류 입니다.

Ionic 5.4.4

```
TypeError: core_1.Cordova is not a function
    at Object../node_modules/ionic-plugin-naver/src/index.js (..\node_modules\ionic-plugin-naver\src\index.js:53:1)
    at __webpack_require__ (..\www\runtime-es2015.js:85:31)
    at Module../src/app/app.module.ts (..\www\main-es2015.js:1277:78)
    at __webpack_require__ (..\www\runtime-es2015.js:85:31)
    at Module../src/main.ts (..\www\main-es2015.js:2895:74)
    at __webpack_require__ (..\www\runtime-es2015.js:85:31)
    at Object.0 (..\www\main-es2015.js:2918:19)
    at __webpack_require__ (..\www\runtime-es2015.js:85:31)
    at checkDeferredModules (..\www\runtime-es2015.js:46:24)
    at Array.webpackJsonpCallback [as push] (..\www\runtime-es2015.js:33:20)
```

**Comment by bbangkwan** [comment]
저도 동일한 현상이 나타나는데 혹시 해결방법 알려주실 수 있으신가요??

**Comment by tree1891** [comment]
오래되어서 정상인지는 모르겠네요.

ionic-plugin-naver_index.js

```
import { Injectable } from '@angular/core';
import { cordova, IonicNativePlugin } from '@ionic-native/core';

"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
//Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = require("@ionic-native/core");
var core_2 = require("@angular/core");
var Naver = (function (_super) {
    __extends(Naver, _super);
    function Naver() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Naver.prototype.login = function () {
        return cordova(this, 'login', {}, arguments);

    };
    Naver.prototype.logout = function () {
        return cordova(this, 'logout', {}, arguments);
    };
    Naver.prototype.logoutAndDeleteToken = function () {
        return cordova(this, 'logoutAndDeleteToken', {}, arguments);
    };
    Naver.prototype.refreshAccessToken = function () {
        return cordova(this, 'refreshAccessToken', {}, arguments);
    };
    Naver.prototype.getState = function () {
        return cordova(this, 'getState', {}, arguments);
    };
    Naver.prototype.requestApi = function (url) {
        return cordova(this, 'requestApi', {}, arguments);
    };
    Naver.prototype.requestMe = function () {
        return cordova(this, 'requestMe', {}, arguments);
    };
    Naver.pluginName = 'Naver';
    Naver.plugin = 'cordova-plugin-naver';
    Naver.pluginRef = 'Naver';
    Naver.platforms = ['Android'];
    Naver = __decorate([
        Injectable()
    ], Naver);
    return Naver;
}(IonicNativePlugin));
export { Naver };
```
